### ISSUE TITLE
Share language

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#101]
Can we talk about these:

'share' vs. 'create new dat' 

and 

'download' or 'add' vs. 'import new dat'

**Comment by yoshuawuyts** [comment]
Some thoughts:

- I feel "share" means you share a dat with other folks - I think this one's clear
- I feel "create new dat" means you create a new dat repository out of a directory. I'd prefer we stick to "create new (dat) repository" as that's the language we're using in the whitepaper
- I don't think "download" is a good word in the context of dat, as we're all about live data and "download" feels like a one-off action that is done at some point. The best we can be is "in sync", never "done"
- I think "import" is pretty clear that it comes from somewhere outside of your own system; "add" could more easily be confused with "create"

I also think we should pick between talking about "dats" or "repositories" - personally I dislike the word "dats" as it doesn't describe what it is. The word "repositories" also feels quite generic, possibly to be confused with "git repositories". I kind of wish we talked about "archives" as that's what hyperdrive exposes and can hardly be confused with anything else - but that's not the language we're using in the whitepaper.

Hope sharing my opinions on words was somewhat useful (:

**Comment by Kriesse** [comment]
### Share vs. Create:

`Create New Dat`: A user creates a new dat out of a repository. This implies the user starts to "share" data.
`Share Dat Link`: A users gets a dat link to copy&past, so they can share it (i.e. send the link to someone). (Note we don't currently use the word "share" in the UI) 

I can see how 1) the action to "share a link" and 2) the implied data sharing of "create new dat" are similar sounding and might be confusing.
How about we make sure to always call it "Get Dat Link" or "Copy Dat Link" instead of "Share Dat"? We don't offer any advanced sharing options anyway (like tweeting it or something).

`Create new dat` seems clear to me.

### Download or Add vs. Import New Dat

I agree with this: 
> I think "import" is pretty clear that it comes from somewhere outside of your own system; "add" could more easily be confused with "create"

### Dat vs Repository vs Archive

I like `Dat`, but this is clearly hoping that we can coin a term for users to pick up, instead of using an existing concept. 
If we opt against trying to make `Dat` a thing, I prefer `Archive` over other options. Seems most descriptive + intuitive and I've heard it come up naturally in conversations with potential users.

**Comment by yoshuawuyts** [comment]
@karissa any further thoughts on this?

**Comment by karissa** [comment]
@Kriesse and I are now in the same place so we can chat in person a bit more. I generally agree with  the comments here

**Comment by yoshuawuyts** [comment]
nice, keen to hear what y'all arrive on :D

**Comment by yoshuawuyts** [comment]
ping @karissa @Kriesse what'd you decide on?

**Comment by yoshuawuyts** [comment]
- I believe we're calling it `import` - the CLI has `dat clone` and `dat sync` - our import is kind of both combined I guess?
- I believe we're calling them "dat archives" or "dats" for short. There's now also https://github.com/datprotocol
- We're calling making a new dat `create`

Closing for now as there hasn't been a lot of activity, feel we've kinda settled on stuff
