### ISSUE TITLE
deleting the second time never calls callback

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#228]
Check out this branch, which is just master but also has debugging statements:
https://github.com/datproject/dat-desktop/tree/delete-debug

1. Create a dat
2. Create another dat.
3. Delete one dat.
4. Delete the second dat (nothing happens, but you see `onexit` called in the console). We would expect to see `ondelete` called in the console! So that means the confirm modal is never calling `ondelete` callback the second time. Why is that?

<img width="533" alt="screen shot 2017-02-13 at 6 19 38 pm" src="https://cloud.githubusercontent.com/assets/633012/22912250/017d65d2-f219-11e6-89e9-ccc2513b1ea9.png">

**Comment by yoshuawuyts** [comment]
Ah yeah this is definitely choo related - `yo-yo` to be specific. If I'm not mistaken it's because the copier copies the events over instead of leaving the child nodes as-is.

I think a possible fix could be to assign a unique `id` to each node so it's reordered rather than recreated and events aren't copied over.

If that doesn't work, I think `nanomorph` should help solve this in the near future as it does event copying a bit differently.

**Comment by karissa** [comment]
I'm still seeing the bug unfortunately

**Comment by yoshuawuyts** [comment]
This should be fixed now; feel free to reopen if it's still the case :sparkles:
