### ISSUE TITLE
Fix the link to .dmg file

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#299]
Right now, when you click 'download for mac' on the website, it goes to the Github releases page, which shows Linux as the first item. It is pretty confusing for new users to find the mac release.

**Comment by yoshuawuyts** [comment]
I've updated the labels of `latest-release` and `pre-release`. On the next release `1.1.0` should be at the top and people should have no trouble downloading it. We've discussed it before and think it's probably good enough for now (:

**Comment by karissa** [comment]
It was a problem that came up that was pretty troubling for users during user testing that led to them needing help to find the mac version for download.

**Comment by maxogden** [comment]
I don't think we should ever send users to github.com, we should link directly to the .dmg files from our website

**Comment by yoshuawuyts** [comment]
Yeah fair point, after seeing the user flow I totes agree

On Wed, Mar 15, 2017, 18:44 maxogden <notifications@github.com> wrote:

I don't think we should ever send users to github.com, we should link
directly to the .dmg files from our website

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/datproject/dat-desktop/issues/299#issuecomment-286823129>,
or mute the thread

**Comment by karissa** [comment]
OK this is fixed in https://github.com/datproject/datproject.org/commit/88fcf165e0c6bc82c9d9d9dcdff71af1d14ee88c
