### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat-desktop#435]

**Comment by martinheidegger** [comment]
I might be interested in getting Dat Desktop to run on windows. It would be helpful to have hints on how to get started :)

**Comment by juliangruber** [comment]
@martinheidegger the backend part should be running good at this time, but we encountered some front end / DOM problems. If you want to look at it, just `npm install && npm start` in this repo :) Any help is _greatly_ appreciated!

**Comment by juliangruber** [comment]
My current guess is that we need to migrate all elements to latest `nanocomponent`

**Comment by maximousblk** [comment]
A release for windows would be greatly appreciated! Please solve the issues related to windows. Windows users(ME) are looking after for a release for windows operating systems.

**Comment by maximousblk** [comment]
I have no idea how this project works and I want to know. I am interested in testing if there is a windows binary available. I so want this project to succeed but i do not know much about this framework nor am very good at programming(Just a teenager with high aims) so cannot contribute too.

I am just asking for a windows binary ASAP and you(@martinheidegger) wrote "if" instead of "it"

Thanx for replying @martinheidegger

**Comment by okdistribute** [comment]
There is now a Windows version, see https://github.com/datproject/dat-desktop/releases

Let us know if it works for you!

**Comment by maximousblk** [comment]
That is awesome. I was still waiting. Late but finally there.
