### ISSUE TITLE
Ask for confirmation before removing a Dat

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#86]
The user should understand that they're removing the dat, let's give them a warning. Will work on UI.

- [ ] add modal dialogue
- [ ] style it

**Comment by karissa** [comment]
Yeah, also we should consider whether or not it removes files from the filesystem. WebTorrent doesn't remove files, but DropBox does (via the filesystem).

I'm more inclined to err on the side of not removing the files directly since this UI is more similar to WebTorrent (UI delete button) than DropBox (filesystem) right now.

**Comment by juliangruber** [comment]
I agree with not removing files automatically, but what about adding a check box to remove files in the confirmation dialogue?

**Comment by karissa** [comment]
Let's wait for a user to ask for it

**Comment by Kriesse** [comment]
Can I get a modal here?
When the user clicks on the trash icon, this modal should come up.
Only after the user clicks the "Yes" button, the Dat gets deleted.

## Mockup:

![image](https://cloud.githubusercontent.com/assets/53684/20927229/ac7ca85c-bc14-11e6-8ffb-1ecd8639d679.png)

**Comment by yoshuawuyts** [comment]
Looks great!

**Comment by karissa** [comment]
+1!!!

**Comment by Kriesse** [comment]
@yoshuawuyts Can you help me to get the confirmation modal in place? Styling should be quick then :)

**Comment by karissa** [comment]
I started it here: #118

**Comment by yoshuawuyts** [comment]
tested and working! - closing this issue :tada: - thanks @karissa :sparkles:
